server:
  port: 7070

spring:
  application:
    name: alibaba-config-server
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.168.60:8848
    config:
      server:
        git:
          uri: https://gitee.com/liuxinjie123/springcloud-config.git
          search-paths: /

